# Golf HILS Simulator Configuration
# Copy this file to simulator_config.yaml and modify as needed

# Serial Communication Settings
serial:
  port: "/dev/ttyUSB0"    # Serial port for M5StickC Plus2 connection
  baud_rate: 115200       # Baud rate for serial communication
  timeout: 1.0            # Serial timeout in seconds

# Display Settings
display:
  mode: "live"            # Options: live, headless, both
  screen_size: [1024, 768]  # Display resolution [width, height]
  figure_size: [12, 8]    # Matplotlib figure size [width, height]
  fullscreen: false       # Run in fullscreen mode

# Database Settings
database:
  path: "golf_hils_data.db"  # SQLite database file path
  backup_interval: 3600   # Backup interval in seconds (1 hour)

# Session Settings
session:
  location: "Practice Range"
  weather: "Unknown"
  auto_export: true       # Auto-export data after each session

# Simulation Settings
simulation:
  physics_timestep: 0.01  # Physics simulation timestep in seconds
  air_density: 1.225      # Air density in kg/m³
  gravity: 9.81           # Gravity in m/s²

# Club Specifications
clubs:
  Driver:
    loft: 10.5
    max_distance: 250
    typical_spin: 2500
  3-Iron:
    loft: 21
    max_distance: 180
    typical_spin: 4000
  5-Iron:
    loft: 27
    max_distance: 160
    typical_spin: 5000
  7-Iron:
    loft: 34
    max_distance: 140
    typical_spin: 6000
  9-Iron:
    loft: 42
    max_distance: 120
    typical_spin: 7000
  P-Wedge:
    loft: 46
    max_distance: 100
    typical_spin: 8000
  S-Wedge:
    loft: 56
    max_distance: 80
    typical_spin: 9000
  Putter:
    loft: 4
    max_distance: 30
    typical_spin: 500

# Logging Settings
logging:
  level: "INFO"           # Options: DEBUG, INFO, WARNING, ERROR
  file: "golf_hils.log"   # Log file path
  max_size: 10485760      # Max log file size in bytes (10MB)
  backup_count: 5         # Number of log file backups to keep